[package]
name = "starkescrow"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = ">=2.8.0"
snforge_std = "0.55.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.20.0" }

[[target.starknet-contract]]
sierra = true
casm = true

[tool.snforge]
exit_first = true
